---

- debug:
    msg: "******************** SENAITE ZSH [START] ********************"

- name: "Run ZSH Role"
  include_role:
    name: gantsign.oh-my-zsh

- name: write custom .zshrc for users
  become: yes
  become_user: '{{ user.username }}'
  template:
    src: zshrc.j2
    dest: '~{{ user.username }}/.zshrc'
    backup: no
    mode: 'u=rw,go=r'
  with_items: '{{ users }}'
  when: "((user.oh_my_zsh | default({})).install | default(oh_my_zsh_install)) | bool"
  loop_control:
    loop_var: user
    label: '{{ user.username }}'

- debug:
    msg: "******************** SENAITE ZSH [DONE] ********************"
