---

- debug:
    msg: "******************** SENAITE HA-PROXY [START] ********************"

- include_role:
    name: geerlingguy.haproxy

- name: SHELL | Get HAPROXY Version
  shell: haproxy -v | grep -o "[0-9]\.[0-9]" | head -1
  register: haproxy_version
  tags:
    - senaite-haproxy-version

- debug:
    msg: "HAProxy Version -> {{ haproxy_version.stdout }}"
  tags:
    - senaite-haproxy-version

- name: Copy HAProxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
  notify: restart haproxy
  tags: senaite-haproxy

- debug:
    msg: "******************** SENAITE HA-PROXY [DONE] ********************"
